version: '3'
services:
  mysql:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
    networks:
      - principal
  php:
    build: ./api
    ports:
      - "8000:8000"
    networks:
      - principal
  angular:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - principal
networks:
  principal:
