version: '2'

services:
    php:
        container_name: ecommerce_php
        image: tuxmate/php:testing
        ports:
            - "8080:8080" # frontend
            - "8081:8081" # api
        environment:
            - TERM=xterm
            - PHINX_BIN_DIR=/www/ecommerce/vendor/bin/phinx
        volumes:
            - ./docker/nginx/ecommerce-frontend.conf:/etc/nginx/conf.d/ecommerce-frontend.conf
            - ./docker/nginx/ecommerce-api.conf:/etc/nginx/conf.d/ecommerce-api.conf
            - ./docker/php/www.conf:/etc/php/7.1/fpm/pool.d/www.conf
            - ./docker/php/php.ini:/etc/php/7.1/fpm/php.ini
            - ./public/views:/www/ecommerce-frontend
            - .:/www/ecommerce
            - ./public/assets/images/:/www/ecommerce/public/assets/images/
        links:
            - mariadb
            - phpmyadmin

    mariadb:
        image: mariadb:10.1.18
        environment:
            - TERM=xterm
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=ecommerce
        volumes:
            - ./db_data:/var/lib/mysql
        ports:
            - "3308:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - TERM=xterm
            - MYSQL_ROOT_PASSWORD=admin
            - PMA_HOST=mariadb
        ports:
            - "9092:80"
