version: '3'
services:
  php:
    # environment:
      # DB_CONNECTION: mysql
      # DB_HOST: ecommerce.cnc0cefnqksq.sa-east-1.rds.amazonaws.com
      # DB_PORT: 3306
      # DB_DATABASE: ecommerce
      # DB_USERNAME: root
      # DB_PASSWORD: Coca-Cola1
    build: ./api
    ports:
      - "9000:9000"
    networks: 
      - principal
  angular:
    depends_on:
      - php
    build: ./frontend
    ports:
      - "3000:3000"
    networks: 
      - principal
networks:
  principal:
    driver: bridge
