-- phpMyAdmin SQL Dump
-- version 4.8.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: 02-Jun-2019 às 21:12
-- Versão do servidor: 10.1.31-MariaDB
-- PHP Version: 7.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `php_test`
--
GRANT USAGE ON *.* TO 'luis_dias'@'localhost' IDENTIFIED BY PASSWORD '*877B8250C9D05C1FB65BA9882AB1199F08361698';
GRANT ALL PRIVILEGES ON `php\_test`.* TO 'luis_dias'@'localhost';

CREATE DATABASE IF NOT EXISTS `php_test` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `php_test`;



-- --------------------------------------------------------

--
-- Estrutura da tabela `products`
--

DROP TABLE IF EXISTS `products`;
CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_retailer` int(11) NOT NULL,
  `name` varchar(127) NOT NULL,
  `price` decimal(8,2) NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `description` text,
  PRIMARY KEY (`id`),
  KEY `id_retailer` (`id_retailer`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=latin1;

--
-- Extraindo dados da tabela `products`
--

INSERT INTO `products` (`id`, `id_retailer`, `name`, `price`, `image`, `description`) VALUES
(1, 2, 'Product 1', '820.00', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(2, 4, 'Product 2', '428.10', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(3, 3, 'Product 3', '932.40', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(4, 3, 'Product 4', '862.70', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(5, 3, 'Product 5', '135.50', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(6, 1, 'Product 6', '244.10', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(7, 1, 'Product 7', '634.20', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(8, 6, 'Product 8', '852.50', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(9, 3, 'Product 9', '489.10', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(10, 2, 'Product 10', '620.80', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(11, 3, 'Product 11', '394.10', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(12, 4, 'Product 12', '900.80', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(13, 4, 'Product 13', '567.60', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(14, 5, 'Product 14', '676.60', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(15, 5, 'Product 15', '746.90', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(16, 3, 'Product 16', '102.80', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(17, 2, 'Product 17', '231.00', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(18, 5, 'Product 18', '462.90', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.'),
(19, 5, 'Product 19', '716.80', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.');

-- --------------------------------------------------------

--
-- Estrutura da tabela `retailers`
--

DROP TABLE IF EXISTS `retailers`;
CREATE TABLE IF NOT EXISTS `retailers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(127) NOT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `description` text,
  `website` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

--
-- Extraindo dados da tabela `retailers`
--

INSERT INTO `retailers` (`id`, `name`, `logo`, `description`, `website`) VALUES
(1, 'Retailer 1', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.', 'https://retailer1.com.br'),
(2, 'Retailer 2', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.', 'https://retailer2.com.br'),
(3, 'Retailer 3', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.', 'http://retailer3.com.br'),
(4, 'Retailer 4', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.', NULL),
(5, 'Retailer 5', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed malesuada nibh. Phasellus iaculis a mauris at aliquet. Praesent a blandit nisi. Donec pretium, quam eu tempor maximus, velit ipsum ultrices dui, ut tempus ex ex at quam. Nulla hendrerit tincidunt eleifend. Donec velit ipsum, commodo a arcu sit amet, consectetur mollis purus. Sed arcu quam, accumsan id molestie vel, tempor sed nulla. Donec eu odio eleifend, tincidunt ligula fringilla, egestas sem. In hac habitasse platea dictumst. Suspendisse quis purus enim. Donec eget mi justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut condimentum vel lectus eget ornare. Nam et est ac odio sagittis tincidunt vel in ipsum. Morbi cursus turpis purus, nec scelerisque purus vestibulum vitae. Integer accumsan nulla sem, et rutrum magna convallis et.', 'https://retailer5.com.br');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
